version: 2.1

executors:
  ruby:
    working_directory: /data
    docker:
      - image: ruby:2.6.3-slim-stretch

jobs:
  build:
    executor: ruby

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.

workflows:
  version: 2
  sample:
    jobs:
      - build